apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: brillar-test-app
  name: brillar-test-app
spec:
  replicas: 2
  selector:
    matchLabels:
      run: brillar-test-app
  template:
    metadata:
      labels:
        run: brillar-test-app
    spec:
      containers:
      - image: gcr.io/gcp-cicd-brillar/brillar-test-app:latest #Replace [PROJECT-ID] accordingly
        name: brillar-test-app
        ports:
        - containerPort: 8080
